language: node_js
node_js:
  - 0.12

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - npm run test-single-run




